# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='execute_result',
            field=models.TextField(verbose_name='查询结果的JSON格式'),
        ),
    ]
