# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquery', '0003_workflow_cluster_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='field_names',
            field=models.CharField(default='', max_length=2000, verbose_name='列名'),
        ),
    ]
