# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquery', '0004_workflow_field_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='execute_result',
            new_name='query_result',
        ),
    ]
