# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquery', '0006_remove_workflow_finish_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='query_result',
            new_name='query_results',
        ),
    ]
