# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
