# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170611_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table='account_users',
        ),
    ]
