# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster_config',
            name='cluster_hosts',
            field=models.CharField(max_length=100, verbose_name='主从库地址JSON格式'),
        ),
    ]
