# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0002_auto_20170612_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster_config',
            name='cluster_password',
            field=models.CharField(max_length=300, verbose_name='登录集群的密码'),
        ),
        migrations.AlterField(
            model_name='cluster_config',
            name='cluster_port',
            field=models.IntegerField(default=3306, verbose_name='集群端口'),
        ),
        migrations.AlterField(
            model_name='cluster_config',
            name='cluster_user',
            field=models.CharField(max_length=15, verbose_name='登录集群的用户名'),
        ),
    ]
