# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0003_auto_20170612_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_type', models.CharField(max_length=10, verbose_name='集群类型')),
            ],
        ),
        migrations.AlterField(
            model_name='cluster_config',
            name='cluster_type',
            field=models.IntegerField(default=1, max_length=10, verbose_name='集群类型'),
        ),
    ]
