# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0007_auto_20170613_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster_config',
            name='cluster_type',
            field=models.IntegerField(default=1, verbose_name='集群类型'),
        ),
    ]
