# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0008_auto_20170613_1855'),
    ]

    operations = [
    ]
