# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0009_auto_20170613_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster_config',
            name='is_online',
            field=models.IntegerField(default=1, verbose_name='集群状态'),
        ),
    ]
