# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0010_cluster_config_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster_config',
            old_name='is_online',
            new_name='cluster_status',
        ),
    ]
