# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0012_auto_20170625_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysql_cluster_config',
            old_name='cluster_type',
            new_name='cluster_role',
        ),
    ]
