# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0013_auto_20170625_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='mongodb_cluster_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('cluster_role', models.IntegerField(default=1, verbose_name='集群role')),
                ('cluster_hosts', models.CharField(max_length=100, verbose_name='主从库地址JSON格式')),
                ('cluster_port', models.IntegerField(default=3306, verbose_name='集群端口')),
                ('cluster_user', models.CharField(max_length=15, verbose_name='登录集群的用户名')),
                ('cluster_password', models.CharField(max_length=300, verbose_name='登录集群的密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cluster_status', models.IntegerField(default=1, verbose_name='集群状态')),
            ],
        ),
        migrations.CreateModel(
            name='redis_cluster_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('cluster_role', models.IntegerField(default=1, verbose_name='集群role')),
                ('cluster_hosts', models.CharField(max_length=100, verbose_name='主从库地址JSON格式')),
                ('cluster_port', models.IntegerField(default=3306, verbose_name='集群端口')),
                ('cluster_user', models.CharField(max_length=15, verbose_name='登录集群的用户名')),
                ('cluster_password', models.CharField(max_length=300, verbose_name='登录集群的密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cluster_status', models.IntegerField(default=1, verbose_name='集群状态')),
            ],
        ),
    ]
