# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0014_mongodb_cluster_config_redis_cluster_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mongodb_cluster_config',
            old_name='cluster_hosts',
            new_name='cluster_host',
        ),
        migrations.RenameField(
            model_name='mysql_cluster_config',
            old_name='cluster_hosts',
            new_name='cluster_host',
        ),
        migrations.RenameField(
            model_name='redis_cluster_config',
            old_name='cluster_hosts',
            new_name='cluster_host',
        ),
    ]
