# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0015_auto_20170625_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongodb_cluster_config',
            name='cluster_host',
            field=models.CharField(max_length=100, verbose_name='实例地址'),
        ),
        migrations.AlterField(
            model_name='mysql_cluster_config',
            name='cluster_host',
            field=models.CharField(max_length=100, verbose_name='实例地址'),
        ),
        migrations.AlterField(
            model_name='redis_cluster_config',
            name='cluster_host',
            field=models.CharField(max_length=100, verbose_name='实例地址'),
        ),
    ]
