# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0016_auto_20170726_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='mysql_cluster_metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('cluster_port', models.IntegerField(default=3306, verbose_name='集群端口')),
                ('table_schema', models.CharField(default='', max_length=64)),
                ('table_name', models.CharField(default='', max_length=64)),
                ('table_type', models.CharField(default='', max_length=64)),
                ('engine', models.CharField(default='', max_length=64)),
                ('row_format', models.CharField(default='', max_length=20)),
                ('table_rows', models.BigIntegerField()),
                ('avg_row_length', models.PositiveIntegerField()),
                ('data_length', models.SmallIntegerField()),
                ('max_data_length', models.URLField()),
                ('index_length', models.BinaryField()),
                ('data_free', models.UUIDField()),
                ('auto_increment', models.GenericIPAddressField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('table_collation', models.CharField(default='', max_length=32)),
                ('create_options', models.CharField(default='', max_length=255)),
                ('table_comment', models.CharField(default='', max_length=2048)),
            ],
        ),
    ]
