# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconfig', '0019_auto_20170727_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql_cluster_metadata',
            name='create_statement',
            field=models.TextField(default=''),
        ),
    ]
