# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('master_host', models.CharField(max_length=20, verbose_name='主库地址')),
                ('master_port', models.IntegerField(default=3306, verbose_name='主库端口')),
                ('master_user', models.CharField(max_length=15, verbose_name='登录主库的用户名')),
                ('master_password', models.CharField(max_length=300, verbose_name='登录主库的密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=50, verbose_name='工单内容')),
                ('engineer', models.CharField(max_length=15, verbose_name='发起人')),
                ('review_man', models.CharField(max_length=50, verbose_name='主副审核人JSON格式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.IntegerField(verbose_name='工单状态')),
                ('reject_opinion', models.CharField(default='', max_length=50, verbose_name='驳回意见')),
                ('is_backup', models.IntegerField(default=1, verbose_name='是否备份，0为否，1为是')),
                ('review_content', models.TextField(verbose_name='自动审核内容的JSON格式')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('reviewok_time', models.DateTimeField(blank=True, null=True, verbose_name='人工审核通过的时间')),
                ('sql_content', models.TextField(verbose_name='具体sql内容')),
                ('execute_result', models.TextField(verbose_name='执行结果的JSON格式')),
            ],
        ),
    ]
