# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlreview', '0005_auto_20170617_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='notes',
            field=models.CharField(default='{}', max_length=100, verbose_name='备注 JSON格式'),
        ),
    ]
