# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='users',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
